### ISSUE TITLE
我想知道这个是你个人的还是官方的接口啊

### ISSUE THREAD

**Issue by wei168hua** [dalgurak007/douyumsg#1]
这个是不是官方接口啊

**Comment by itpika** [comment]
不是，这是自己直接连的斗鱼的弹幕服务器，弹幕服务器的地址和连接后具体的数据接收方法，斗鱼文档里面都有。目前官网并没有提供任何语言的SDK，要获取弹幕只有自己连接封装或者网上找开源的包
