### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by vhysug** [dalgurak007/douyumsg#2]
程序执行之后，可以看到内存蹭蹭的往上涨，尝试解决了半天也没有效果，麻烦大佬看下
大约10min内就可以看到内存变化

**Comment by itpika** [comment]
我暂时没有遇到这种情况，不过还是做了一点内存优化，你可以更新下试试。
感谢你的issues

**Comment by vhysug** [comment]
太强了，拿大主播的弹幕测了一个小时，没有OOM的问题；
你改的代码还不是太明白，我再细细研究下；
多谢大佬
